/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as InvariantContractJson } from "../Invariant.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace InvariantTypes {
  export type Fields = {
    protocolFee: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getProtocolFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  InvariantInstance,
  InvariantTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as InvariantTypes.Fields;
  }

  at(address: string): InvariantInstance {
    return new InvariantInstance(address);
  }

  tests = {
    getProtocolFee: async (
      params: Omit<TestContractParams<InvariantTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getProtocolFee", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Invariant = new Factory(
  Contract.fromJson(
    InvariantContractJson,
    "",
    "e4ac1069a1aea968d177741c290e109285ba3771c8df9c94e07d80d328a4c0c3"
  )
);

// Use this class to interact with the blockchain
export class InvariantInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<InvariantTypes.State> {
    return fetchContractState(Invariant, this);
  }

  methods = {
    getProtocolFee: async (
      params?: InvariantTypes.CallMethodParams<"getProtocolFee">
    ): Promise<InvariantTypes.CallMethodResult<"getProtocolFee">> => {
      return callMethod(
        Invariant,
        this,
        "getProtocolFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends InvariantTypes.MultiCallParams>(
    calls: Calls
  ): Promise<InvariantTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Invariant,
      this,
      calls,
      getContractByCodeHash
    )) as InvariantTypes.MultiCallResults<Calls>;
  }
}
